'use strict';

/**
 * createSkillFromHistory Node
 *
 * Creates a skill from code/scripts found in conversation history.
 * Triggered when user says things like "turn that script into a skill" or "create a skill from that code".
 *
 * Flow:
 * 1. Scans conversationHistory for recent code blocks (python, node, bash)
 * 2. Uses LLM to identify which code block matches user's intent
 * 3. Generates proper skill contract (skill.md format)
 * 4. Saves to ~/.thinkdrop/skills/{skillName}/index.cjs
 * 5. Registers skill in DuckDB + user-memory MCP
 */

const fs = require('fs');
const path = require('path');
const os = require('os');

const USER_SKILLS_DIR = path.join(os.homedir(), '.thinkdrop', 'skills');

/**
 * Extract code blocks from conversation history
 */
function extractCodeBlocks(conversationHistory) {
  const blocks = [];
  const codeFenceRegex = /```(\w+)?\n([\s\S]*?)```/g;
  
  for (const msg of conversationHistory.slice(-10)) { // Look at last 10 messages
    const content = msg.content || msg.text || '';
    let match;
    while ((match = codeFenceRegex.exec(content)) !== null) {
      const lang = match[1] || 'text';
      const code = match[2].trim();
      if (code.length > 50) { // Minimum viable code block
        blocks.push({
          lang: lang.toLowerCase(),
          code,
          timestamp: msg.timestamp,
          role: msg.role,
        });
      }
    }
  }
  
  // Return most recent first
  return blocks.reverse();
}

/**
 * Extract synthesized code from previous execution's skillResults
 * This captures Python/Node.js code generated by synthesize steps
 */
function extractCodeFromSkillResults(skillResults) {
  if (!Array.isArray(skillResults) || skillResults.length === 0) {
    return null;
  }
  
  // Look for synthesize steps that produced code
  const codeFenceRegex = /```(?:python|py|node|javascript|js|bash|sh)?\n([\s\S]*?)```/;
  
  for (const result of skillResults) {
    // Check synthesize steps and shell.run steps that might contain synthesized code
    if ((result.skill === 'synthesize' || result.skill === 'shell.run') && result.ok) {
      const output = String(result.stdout || result.result || '');
      
      // Look for code blocks in the output
      const match = output.match(codeFenceRegex);
      if (match && match[1] && match[1].trim().length > 100) {
        const code = match[1].trim();
        // Determine language from fence marker
        const langMatch = output.match(/```(\w+)/);
        const lang = langMatch ? langMatch[1].toLowerCase() : 'text';
        
        return {
          lang: lang === 'py' ? 'python' : lang === 'js' ? 'javascript' : lang,
          code,
          source: result.skill,
        };
      }
    }
  }
  
  return null;
}

/**
 * Extract code from _lastShellRun (last shell execution state)
 * This captures Python/Node.js code saved in state._lastShellRun
 * Similar to planSkillsV2.js logic
 */
function extractCodeFromLastShellRun(_lastShellRun) {
  if (!_lastShellRun) {
    return null;
  }
  
  // Check if last execution was shell.run with Python
  if (_lastShellRun.skill === 'shell.run') {
    const cmd = _lastShellRun.args?.cmd;
    const argv = _lastShellRun.args?.argv;
    
    if (cmd === 'python3' && Array.isArray(argv) && argv.length > 1) {
      // Extract Python code from argv (skip the first arg which is usually '-c' or script path)
      const pythonCode = argv.slice(1).join(' ');
      if (pythonCode.length > 100) {
        return {
          lang: 'python',
          code: pythonCode,
          source: 'shell.run',
        };
      }
    }
  }
  
  // Also check stdout/result for code blocks (in case code was synthesized and output)
  const output = String(_lastShellRun.stdout || _lastShellRun.result || '');
  const codeFenceRegex = /```(?:python|py|node|javascript|js|bash|sh)?\n([\s\S]*?)```/;
  const match = output.match(codeFenceRegex);
  if (match && match[1] && match[1].trim().length > 100) {
    const code = match[1].trim();
    const langMatch = output.match(/```(\w+)/);
    const lang = langMatch ? langMatch[1].toLowerCase() : 'text';
    
    return {
      lang: lang === 'py' ? 'python' : lang === 'js' ? 'javascript' : lang,
      code,
      source: 'shell.run',
    };
  }
  
  return null;
}

/**
 * Use LLM to identify target code and generate skill interface
 */
async function identifyTargetCode({ userMessage, codeBlocks, conversationHistory, llmBackend, logger }) {
  if (!llmBackend) {
    throw new Error('LLM backend unavailable for skill identification');
  }
  
  // Format code blocks for LLM
  const formattedBlocks = codeBlocks.slice(0, 5).map((b, i) => `
--- CODE BLOCK ${i + 1} [${b.lang}] ---
${b.code.slice(0, 800)}
${b.code.length > 800 ? '\n... (truncated)' : ''}
`).join('\n');

  const recentContext = conversationHistory.slice(-6)
    .map(m => `${m.role}: ${(m.content || '').slice(0, 200)}`)
    .join('\n');

  const prompt = `USER REQUEST: "${userMessage}"

RECENT CONVERSATION:
${recentContext}

AVAILABLE CODE BLOCKS:
${formattedBlocks}

TASK: Identify which code block the user wants to turn into a skill, and extract the skill interface.

Respond with ONLY valid JSON:
{
  "targetBlockIndex": 0-4, // which code block matches the request
  "skillName": "descriptive.skill.name", // dot-notation, descriptive
  "description": "One sentence describing what this skill does",
  "inputs": { "argName": "string|number|boolean" }, // detected input parameters
  "runtime": "node|python|bash", // execution runtime
  "schedule": "on_demand", // always on_demand for extracted skills
  "secrets": [] // usually empty for simple scripts
}

Rules:
- skillName must use dot notation (e.g., "extract.image.urls", "word.counter")
- Look at the code to infer inputs (function parameters, argparse, sys.argv)
- runtime: "python" for .py code, "node" for .js/.cjs, "bash" for shell scripts
- If no code blocks match, set targetBlockIndex to -1`;

  try {
    const response = await llmBackend.generateAnswer(
      prompt,
      { query: prompt, context: { systemInstructions: 'You are a skill extraction specialist. Output ONLY valid JSON.', intent: 'command_automate' } },
      { maxTokens: 600, temperature: 0.1, taskType: 'complex' }
    );
    
    // Extract JSON
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error('No JSON in LLM response');
    }
    
    return JSON.parse(jsonMatch[0]);
  } catch (e) {
    logger.warn('[Node:createSkillFromHistory] LLM identification failed:', e.message);
    throw e;
  }
}

/**
 * Wrap code in proper skill structure
 */
function wrapAsSkill(code, iface, logger) {
  const { skillName, runtime, inputs } = iface;
  const inputNames = Object.keys(inputs || {});
  
  if (runtime === 'node' || runtime === 'javascript') {
    // Wrap as Node.js CommonJS module
    return `'use strict';

/**
 * ${iface.description || skillName}
 * 
 * Inputs: ${JSON.stringify(inputs || {})}
 */

module.exports = async function run(args, context) {
  const { ${inputNames.join(', ')} } = args || {};
  const { logger } = context || {};
  
  try {
${code.split('\n').map(l => '    ' + l).join('\n')}
  } catch (error) {
    if (logger) logger.error('[${skillName}] execution failed:', error.message);
    return { ok: false, error: error.message };
  }
};
`;
  } else if (runtime === 'python') {
    // Wrap as Python script that accepts JSON args via stdin
    return `#!/usr/bin/env python3

"""
${iface.description || skillName}

Inputs: ${JSON.stringify(inputs || {})}
"""

import sys
import json

def main():
    # Read args from stdin (JSON)
    try:
        args = json.load(sys.stdin)
    except:
        args = {}
    
${code.split('\n').map(l => '    ' + l).join('\n')}

if __name__ == '__main__':
    main()
`;
  } else {
    // Bash script - pass args as environment variables
    return `#!/bin/bash

# ${iface.description || skillName}
# Inputs: ${JSON.stringify(inputs || {})}

${code}
`;
  }
}

/**
 * Register skill in DuckDB agents.db
 */
async function registerSkillInDb(db, skillName, skillPath, iface, logger) {
  if (!db) {
    logger.warn('[Node:createSkillFromHistory] No DB connection');
    return;
  }
  
  try {
    await db.run(`
      CREATE TABLE IF NOT EXISTS skills (
        name TEXT PRIMARY KEY,
        file_path TEXT,
        project_id TEXT,
        trigger TEXT,
        schedule TEXT,
        runtime TEXT,
        secrets TEXT,
        inputs TEXT,
        outputs TEXT,
        status TEXT,
        created_at TEXT,
        updated_at TEXT
      )
    `);
    
    await db.run(
      `INSERT INTO skills (name, file_path, project_id, trigger, schedule, runtime, secrets, inputs, outputs, status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(name) DO UPDATE SET
         file_path=excluded.file_path, trigger=excluded.trigger,
         schedule=excluded.schedule, status=excluded.status, updated_at=excluded.updated_at`,
      skillName,
      skillPath,
      null, // project_id
      iface.description || '',
      iface.schedule || 'on_demand',
      iface.runtime || 'node',
      JSON.stringify(iface.secrets || []),
      JSON.stringify(iface.inputs || {}),
      JSON.stringify(iface.outputs || {}),
      'ready',
      new Date().toISOString(),
      new Date().toISOString()
    );
    
    logger.info('[Node:createSkillFromHistory] Registered skill in DuckDB', { skillName });
  } catch (e) {
    logger.warn('[Node:createSkillFromHistory] DuckDB registration failed:', e.message);
  }
}

/**
 * Register skill in user-memory MCP
 */
async function registerInMemoryMcp(skillName, iface, skillPath, logger) {
  try {
    const http = require('http');
    const memPort = parseInt(process.env.MEMORY_SERVICE_PORT || '3001', 10);
    const memApiKey = process.env.MCP_USER_MEMORY_API_KEY || process.env.USER_MEMORY_API_KEY || process.env.MCP_API_KEY || '';
    
    // Build contractMd with YAML frontmatter
    const inputsYaml = Object.entries(iface.inputs || {})
      .map(([k, v]) => `  ${k}: ${v}`)
      .join('\n');
    
    const contractMd = `---
name: ${skillName}
description: ${iface.description || skillName}
runtime: ${iface.runtime || 'node'}
trigger: "${iface.description || ''}"
schedule: ${iface.schedule || 'on_demand'}
${iface.secrets?.length ? `secrets:\n${iface.secrets.map(s => `  - ${s}`).join('\n')}` : 'secrets: []'}
inputs:
${inputsYaml || '  # no inputs required'}
outputs:
  result: string
---

Skill file: ${skillPath}
`;
    
    const body = JSON.stringify({
      version: 'mcp.v1',
      service: 'user-memory',
      action: 'skill.install',
      payload: { contractMd },
      requestId: `skill-history-${Date.now()}`
    });
    
    await new Promise((resolve) => {
      const req = http.request({
        hostname: '127.0.0.1',
        port: memPort,
        path: '/skill.install',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
          ...(memApiKey ? { 'Authorization': `Bearer ${memApiKey}` } : {})
        },
        timeout: 8000,
      }, (res) => { res.resume(); res.on('end', resolve); });
      
      req.on('error', () => resolve());
      req.on('timeout', () => { req.destroy(); resolve(); });
      req.write(body);
      req.end();
    });
    
    logger.info('[Node:createSkillFromHistory] Registered skill in user-memory MCP', { skillName });
  } catch (e) {
    logger.warn('[Node:createSkillFromHistory] MCP registration failed:', e.message);
  }
}

/**
 * Generate skill code from natural language description
 * TRIES: Python first, then Node.js, then Shell
 */
async function generateSkillFromDescription({ userMessage, llmBackend, logger }) {
  const SYSTEM_PROMPT = `You are a skill code generator for a desktop automation system.

Given a user's description of what they want a skill to do, generate COMPLETE, WORKING code.

**PRIORITY ORDER (TRY THESE IN SEQUENCE):**
1. **PYTHON** (preferred) - Generate Python 3 code using standard library
2. **NODE.JS** - If Python can't handle it, generate Node.js CommonJS  
3. **SHELL/BASH** - If Node.js can't handle it, generate bash script

**OUTPUT FORMAT:**
Return JSON with the FIRST working solution:
{
  "runtime": "python" | "node" | "shell",
  "skillName": "descriptive.skill.name",
  "description": "One sentence description",
  "inputs": { "argName": "string|number|boolean" },
  "code": "complete working code here"
}

**PYTHON SKILL TEMPLATE:**
- Read args from stdin as JSON
- Use standard library only (os, sys, json, datetime, pathlib, re)
- Output result as JSON to stdout
- Include error handling with try/except
- For file watching: use os.listdir + stat comparisons (no watchdog needed)
- For scheduling: skills run on-demand, external scheduler handles cron

**NODE.JS SKILL TEMPLATE:**
- module.exports = async function run(args, context) { ... }
- Use fs, path, os built-ins
- Return { ok: true/false, output/error: ... }

**SHELL SKILL TEMPLATE:**
- Read JSON args from stdin
- Use jq or grep/sed for parsing
- Output JSON result

**EXAMPLES:**
- "Track new files on desktop" → Python: os.listdir + stat.ctime comparison + markdown logging
- "Count words in files" → Python: read file + split + len
- "Send webhook" → Node.js: https request
- "List directory" → Shell: ls -la | jq

CRITICAL: Generate COMPLETE, RUNNABLE code with error handling.`;

  const prompt = `Create a skill for: "${userMessage}"

Generate working code (Python preferred, fallback to Node.js or Shell if needed).

Output ONLY JSON with runtime, skillName, description, inputs, and code.`;

  try {
    const response = await llmBackend.generateAnswer(
      prompt,
      { query: prompt, context: { systemInstructions: SYSTEM_PROMPT, intent: 'command_automate' } },
      { maxTokens: 2000, temperature: 0.2, taskType: 'complex' }
    );
    
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('No JSON in LLM response');
    
    return JSON.parse(jsonMatch[0]);
  } catch (e) {
    logger.error('[Node:createSkillFromHistory] Failed to generate skill from description:', e.message);
    throw e;
  }
}

/**
 * Main node function - handles both "from history" and "from description"
 */
module.exports = async function createSkillFromHistory(state) {
  const {
    message,
    resolvedMessage,
    conversationHistory,
    skillResults,
    llmBackend,
    logger,
    mcpAdapter,
  } = state;
  
  const userMessage = resolvedMessage || message || '';
  logger.info('[Node:createSkillFromHistory] Creating skill from conversation history');
  
  try {
    // Step 1: Extract code blocks from conversation
    const codeBlocks = extractCodeBlocks(conversationHistory || []);
    
    // CASE 1: No code blocks found - try skillResults, then create from description
    if (codeBlocks.length === 0) {
      logger.info('[Node:createSkillFromHistory] No code blocks found - checking skillResults from previous execution');
      
      // Try to extract synthesized code from previous execution's skillResults OR _lastShellRun
      // CRITICAL FIX: Also check _lastShellRun which persists across executions (like planSkillsV2 uses)
      const synthesizedCode = extractCodeFromSkillResults(skillResults) 
        || extractCodeFromLastShellRun(state._lastShellRun);
      
      if (synthesizedCode) {
        logger.info(`[Node:createSkillFromHistory] Found synthesized code from ${synthesizedCode.source} (${synthesizedCode.lang})`);
        
        // Use the synthesized code directly
        const skillName = deriveSkillName(userMessage);
        const runtime = synthesizedCode.lang === 'python' ? 'python' : 
                        synthesizedCode.lang === 'javascript' ? 'node' : 'shell';
        const fileExt = runtime === 'python' ? 'index.py' : 
                        runtime === 'shell' ? 'index.sh' : 'index.cjs';
        
        const dirName = skillName.replace(/\./g, '_');
        const skillDir = path.join(USER_SKILLS_DIR, dirName);
        const skillPath = path.join(skillDir, fileExt);
        
        // Create interface for wrapping
        const iface = {
          skillName,
          description: userMessage.slice(0, 100),
          runtime,
          inputs: {},
          outputs: { result: 'string' },
          secrets: [],
          schedule: 'on_demand',
        };
        
        // Wrap the code as a skill
        const wrappedCode = wrapAsSkill(synthesizedCode.code, iface, logger);
        
        // Write code to file
        fs.mkdirSync(skillDir, { recursive: true });
        fs.writeFileSync(skillPath, wrappedCode, 'utf8');
        
        const db = mcpAdapter?.db || state.db;
        await registerSkillInDb(db, skillName, skillPath, iface, logger);
        await registerInMemoryMcp(skillName, iface, skillPath, logger);
        
        return {
          ...state,
          answer: `Created ${runtime} skill "${skillName}" from the synthesized code in your previous execution.\n\n**Description:** ${userMessage.slice(0, 100)}\n**Runtime:** ${runtime}\n**Source:** ${synthesizedCode.source} step\n\nThe skill is now available via \`external.skill\` with name "${skillName}".`,
          commandExecuted: true,
          skillCreated: { name: skillName, path: skillPath, interface: iface },
        };
      }
      
      // No synthesized code found - fall back to LLM generation
      logger.info('[Node:createSkillFromHistory] No synthesized code found - generating from description (Python-first)');
      
      if (!llmBackend) {
        return {
          ...state,
          answer: 'I need an LLM backend to generate a skill from your description. Please try again.',
          commandExecuted: true,
        };
      }
      
      const generated = await generateSkillFromDescription({ userMessage, llmBackend, logger });
      
      if (!generated || !generated.code) {
        return {
          ...state,
          answer: 'I was unable to generate a skill from your description. This might be too complex or require a specific tool that isn\'t available. Could you describe it differently?',
          commandExecuted: true,
        };
      }
      
      const skillName = generated.skillName || `generated.skill.${Date.now()}`;
      const runtime = generated.runtime || 'python';
      const description = generated.description || userMessage.slice(0, 100);
      
      // Determine file extension based on runtime
      const fileExt = runtime === 'python' ? 'index.py' : 
                      runtime === 'shell' ? 'index.sh' : 'index.cjs';
      
      const dirName = skillName.replace(/\./g, '_');
      const skillDir = path.join(USER_SKILLS_DIR, dirName);
      const skillPath = path.join(skillDir, fileExt);
      
      // Write code to file
      fs.mkdirSync(skillDir, { recursive: true });
      fs.writeFileSync(skillPath, generated.code, 'utf8');
      
      // Set execType for external.skill
      const execType = runtime === 'python' ? 'python' : 
                       runtime === 'shell' ? 'shell' : 'node';
      
      // Register in databases
      const iface = {
        skillName,
        description,
        runtime: execType,
        inputs: generated.inputs || {},
        outputs: { result: 'string' },
        secrets: [],
        schedule: 'on_demand',
      };
      
      const db = mcpAdapter?.db || state.db;
      await registerSkillInDb(db, skillName, skillPath, iface, logger);
      await registerInMemoryMcp(skillName, iface, skillPath, logger);
      
      const inputDesc = Object.entries(iface.inputs || {})
        .map(([k, v]) => `${k} (${v})`)
        .join(', ') || 'none';
      
      return {
        ...state,
        answer: `Created ${runtime} skill "${skillName}" from your description.\n\n**Description:** ${description}\n**Runtime:** ${runtime}\n**Inputs:** ${inputDesc}\n\nThe skill is now available via \`external.skill\` with name "${skillName}".`,
        commandExecuted: true,
        skillCreated: { name: skillName, path: skillPath, interface: iface },
      };
    }
    
    logger.debug(`[Node:createSkillFromHistory] Found ${codeBlocks.length} code blocks`);
    
    // Step 2: Use LLM to identify target code and generate interface
    const identification = await identifyTargetCode({
      userMessage,
      codeBlocks,
      conversationHistory,
      llmBackend,
      logger,
    });
    
    if (identification.targetBlockIndex < 0 || identification.targetBlockIndex >= codeBlocks.length) {
      return {
        ...state,
        answer: 'I couldn\'t identify which code block you want to turn into a skill. Could you be more specific about which script?',
        commandExecuted: true,
      };
    }
    
    const targetBlock = codeBlocks[identification.targetBlockIndex];
    const skillName = identification.skillName || `extracted.skill.${Date.now()}`;
    
    logger.info(`[Node:createSkillFromHistory] Creating skill "${skillName}" from ${targetBlock.lang} code block`);
    
    // Step 3: Wrap code as skill
    const iface = {
      skillName,
      description: identification.description || `Skill created from ${targetBlock.lang} script`,
      runtime: identification.runtime || targetBlock.lang,
      inputs: identification.inputs || {},
      outputs: identification.outputs || { result: 'string' },
      secrets: identification.secrets || [],
      schedule: 'on_demand',
    };
    
    const skillCode = wrapAsSkill(targetBlock.code, iface, logger);
    
    // Step 4: Write to disk
    const dirName = skillName.replace(/\./g, '_');
    const skillDir = path.join(USER_SKILLS_DIR, dirName);
    const skillPath = path.join(skillDir, 'index.cjs');
    
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(skillPath, skillCode, 'utf8');
    
    logger.info(`[Node:createSkillFromHistory] Wrote skill to ${skillPath}`);
    
    // Step 5: Register in databases
    const db = mcpAdapter?.db || state.db;
    await registerSkillInDb(db, skillName, skillPath, iface, logger);
    await registerInMemoryMcp(skillName, iface, skillPath, logger);
    
    // Step 6: Return success
    const inputDesc = Object.entries(iface.inputs || {})
      .map(([k, v]) => `${k} (${v})`)
      .join(', ') || 'none';
    
    return {
      ...state,
      answer: `Created skill "${skillName}" from your ${targetBlock.lang} script.\n\n**Description:** ${iface.description}\n**Inputs:** ${inputDesc}\n\nThe skill is now available via \`external.skill\` with name "${skillName}".`,
      commandExecuted: true,
      skillCreated: {
        name: skillName,
        path: skillPath,
        interface: iface,
      },
    };
    
  } catch (error) {
    logger.error('[Node:createSkillFromHistory] Failed:', error.message);
    return {
      ...state,
      answer: `Failed to create skill: ${error.message}. Please try again with more details about which script you'd like to convert.`,
      commandExecuted: true,
    };
  }
};
